version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dollarbaz
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dollarbaz
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  backend:
    build:
      context: ./apps/backend
    restart: on-failure
    env_file:
      - ./env/backend.env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  telegrambot:
    build:
      context: ./apps/telegrambot
    restart: on-failure
    env_file:
      - ./env/telegrambot.env
    depends_on:
      - backend
      - redis

  web:
    build:
      context: ./apps/web
    restart: on-failure
    env_file:
      - ./env/web.env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
  redisdata:
