name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build & push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-backend:latest -f apps/backend/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-backend:latest
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-telegrambot:latest -f apps/telegrambot/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-telegrambot:latest
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-web:latest -f apps/web/Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/dollarbaz-web:latest